services:
  # 1. Base de datos
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "127412"
      POSTGRES_DB: samar_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Backend (Server)
  server:
    build: ./server
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      # Variable especial para que Docker use "db" en vez de "localhost"
      - DOCKER_DB_HOST=db
      # Variables est√°ndar
      - DB_USERNAME=postgres
      - PASSWORD=127412
      - DATABASE=samar_db
      - PORT=5000
      - ACCESS_TOKEN_SECRET=SFGSGDAF5165SDG51V
      - cookieKey=DGH2DSg4TH4VDbD12SFB
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules

  # 3. Frontend (Client)
  client:
    build: ./client
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

# ESTO ES LO QUE DABA ERROR: "volumes" debe estar pegado a la izquierda, igual que "services"
volumes:
  postgres_data:
