services:
  # 1. Base de datos
  db:
    image: postgres:15-alpine
    container_name: samar_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # NOTA: En producción, NO exponemos ports: "5432:5432" por seguridad.
    # Solo el backend podrá ver la base de datos internamente.

    # 2. Backend (API)
  server:
    build: ./server
    container_name: samar_backend
    restart: always
    # No exponemos puertos del backend directamente a internet, Nginx lo hará.
    environment:
      - DOCKER_DB_HOST=samar_db
      - DB_USERNAME=${DB_USERNAME}
      - PASSWORD=${PASSWORD}
      - DATABASE=${DATABASE}
      - PORT=${BACKEND_PORT:-3000}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - cookieKey=${cookieKey}
    depends_on:
      - db

  # 3. Frontend (Nginx + React)
  client:
    build: ./client
    container_name: samar_frontend
    restart: always
    ports:
      # Aquí mapeamos el puerto del servidor (80) al puerto de Nginx (80)
      - "5173:5173"
    depends_on:
      - server

volumes:
  postgres_data:
